# Generated by Django 5.1.3 on 2025-01-02 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.IntegerField()),
                ('position', models.CharField(choices=[('1', 'Andhra Pradesh'), ('2', 'Telangana'), ('3', 'kerala'), ('4', 'Tamil Nadu'), ('5', 'Karnataka')], max_length=1)),
                ('district', models.CharField(max_length=25)),
                ('Adress', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
