# Generated by Django 5.1.3 on 2025-01-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='adress',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buy',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
